### PR TITLE
General library improvements

### PR DESCRIPTION
**Pull request by XVincentX**
Hello folks,
as discussed, here are the improvements I tried to bring into the library

1. Implement correctly the **IDisposable** pattern in order to avoid memory leaks and unreleased resources
2. Get rid of the old **WebRequest** in favor of the async and modern **HttpClient** library

This will definitely break up the API, of course.
Tests also should be rewritten but before go further, I'd like to know your opinion on that.

Would also be great to set sort of CI system, such as [AppVeyor](http://www.appveyor.com)

Regards!

### CODE REVIEW

**Comment by jkodumal** [comment]
Thanks  @XVincentX!

The `IDisposable` changes look good-- as for using `HttpClient`, I think the original motivation for using the old-school `WebRequest` was maximizing compatibility for the SDK. My understanding is that `HttpClient` requires .Net 4.5. I'm not as familiar with the .Net ecosystem, so I don't know how many codebases are still on 4.0-- I'll try to do some research and see if it's really necessary to support 4.0.

**Comment by XVincentX** [comment]
Hey @jkodumal,
`HttpClient` can definitely work without any problems on .NET 4.0
My reason to upgrade was due to the fact that basically 4.5 and 4.5.1 version are just high compatibly upgrades, and there should really be no reason to stick on 4.0.

Since you pointed out the issue, I think would be definitely better to switch to a `PCL` project, in order to make it work on different platform (.NET, Windows Phone and so on)

P.S: The improvements are not over here.

**Comment by jkodumal** [comment]
Thanks, that makes sense-- a `PCL` project does look like the way to go.

**Comment by XVincentX** [comment]
Ok, great but...I did not update the tests (since I was waiting for an OK). They are going to fail probably, and needs to be updated as well.

Also, I think it would be great to set up a CI system (you should, since I do not own the repository).

**Comment by jkodumal** [comment]
Thanks for pointing that out. The tests need to be re-written anyway, as some of them make network calls to our production server. I'm working on updating them now. Appreciate the contribution.

**Comment by XVincentX** [comment]
Great. I will follow the project. It would be great if you could ping me once you're done with that!

**Pull request merged**
