### PR TITLE
Add HttpClientHandler override to LDConfig to allow for proxy configuration etc.

### PR DESCRIPTION
**Pull request by arun251**

### CODE REVIEW

**Comment by jkodumal** [comment]
👍

**Comment by apucacao** [comment]
lgtm

**Comment by ISkomorokh** [comment]
Well, it seems that this option was deleted and now, using latest 3.2.0 it is not possible to work through proxy again :(
Please, add a way to set http client or handler through configuration.

**Comment by drichelson** [comment]
@ISkomorokh This looks like a bad release on our part. We've just released 3.3.0 which brings back the ability to set the http client handler.

**Pull request merged**
