### PR TITLE
Updated to latest versions in order to simplify dependencies

### PR DESCRIPTION
**Pull request by ISkomorokh**
From ([Microsoft.Extensions.Logging.Abstractions v 1.0.2](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions/1.0.2))
_**.NETStandard 1.1**_
System.Collections (>= 4.0.11)
System.Collections.Concurrent (>= 4.0.12)
System.Diagnostics.Debug (>= 4.0.11)
System.Globalization (>= 4.0.11)
System.Linq (>= 4.1.0)
System.Reflection (>= 4.1.0)
System.Resources.ResourceManager (>= 4.0.1)
System.Runtime.Extensions (>= 4.1.0)
System.Runtime.InteropServices (>= 4.1.0)

To ([Microsoft.Extensions.Logging.Abstractions v 1.1.2](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions/1.1.2))
_**.NETStandard 1.1**_
NETStandard.Library (>= 1.6.1)

### CODE REVIEW

**Comment by ISkomorokh** [comment]
@jkodumal , @richardadalton  please, review

**Comment by arun251** [comment]
Hi @ISkomorokh , I will take a look at this.

**Comment by ISkomorokh** [comment]
I believe this issue might be closed afterwards https://github.com/launchdarkly/.net-client/issues/39

**Comment by ISkomorokh** [comment]
@arun251 any progress?

**Comment by ISkomorokh** [comment]
BTW, .Net Standard 2.0 was released :)

**Comment by arun251** [comment]
Thanks @ISkomorokh !

**Pull request merged**
